logging:
  level:
    ROOT: INFO
spring:
  #  profiles:
  #    active: dev
  #    include:
  # Uncomment to activate TLS for the dev profile
  #- tls
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  data:
    mongodb:
      uri: mongodb://mongodb:27017
      database: DiscworlCharacters
server:
  port: 8196
management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      influx:
        db: wizzards
        uri: http://influxdb:8086 # URI of the Influx server. (Default: http://localhost:8086)
        step: 1m # Step size (i.e. reporting frequency) to use. (Default: 1m)
        auto-create-db: false # Whether to create the Influx database if it does not exist before attempting to publish metrics to it. (Default: true)

application:
  springFoxUrl: http://localhost:8196
mongock:
  change-logs-scan-package: be.jvit.discworldcharacter.config.dbmigrations